# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-15 10:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaveDetails', '0001_initial'),
        ('agentWebApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_History', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leaveDetails.LeaveHistory')),
            ],
        ),
    ]
