# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-15 10:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agentWebApp', '0002_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentdetails',
            name='organization_details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agentWebApp.Organization'),
        ),
        migrations.AddField(
            model_name='organization',
            name='name',
            field=models.CharField(default='abc', max_length=10),
        ),
    ]
